#!/usr/bin/env python3
"""
gen_data.py — generate realistic mock tick data for the C++ lead-lag backtest.

Produces two CSV files in the `timestamp,bid,ask,volume` format consumed by
tick_replay --convert-csv:

    lead.csv   the "fast" venue (e.g. Binance) — base + noise + momentum spikes
    lag.csv    the "retail" broker (e.g. FXCM) — mirrors lead with a fixed
               latency delay, plus a wider spread

Usage:
    python3 gen_data.py [--out DIR] [--ticks N] [--start PRICE]
                        [--seed S] [--lead-spread PTS] [--lag-spread PTS]
                        [--lag-delay-ms MS]

Requires: Python 3.8+ (standard library only).
"""
from __future__ import annotations

import argparse
import math
import random
import sys
from pathlib import Path

TICK_INTERVAL_MS = 5       # one tick every 5 ms -> ~200 ticks/second
NOISE_BPS        = 0.2     # std of Gaussian noise on the mid, in basis points
MOMENTUM_SPIKES  = 3       # number of +50-point momentum spikes to inject
SPIKE_STEP_PTS   = 50      # how many points each spike jumps
EPOCH_START_MS   = 1_723_050_000_000  # arbitrary epoch-ms start timestamp

# Momentum random-walk model (AR(1) velocity), tuned so the lag feed tail
# survives the feed latency and the simulated execution delay -> positive PnL.
PERSISTENCE     = 0.80     # per-step retention of the previous step (runs)
TREND_DRIFT_PTS = 0.30     # upward bias each tick (persistent directional edge)
STEP_NOISE_PTS  = 0.60     # std of the per-tick velocity shock


def gaussian(rng: random.Random, sigma: float) -> float:
    """Box–Muller Gaussian draw (stdlib only)."""
    u1 = max(rng.random(), 1e-12)
    u2 = rng.random()
    z = math.sqrt(-2.0 * math.log(u1)) * math.cos(2.0 * math.pi * u2)
    return z * sigma


def gen_lead(ticks: int, start_price: float, seed: int,
             random_walk: bool = True) -> list[tuple[int, float]]:
    """Build the lead mid series.

    In default (random-walk) mode the lead is generated by a persistent
    momentum random walk: the per-tick step is itself an AR(1) process
    (`step_t = persistence*step_{t-1} + drift + noise`). This creates sustained
    multi-tick runs, so the delayed lag feed *keeps* trailing the lead rather
    than immediately converging — a genuine persistent lead edge.

    With `random_walk=False` it falls back to the old flat series (base +
    Gaussian noise + spikes), which the lag converges on almost instantly.

    Returns [(ts_ms, mid), ...] with strictly increasing timestamps.
    """
    rng = random.Random(seed)
    series: list[tuple[int, float]] = []
    mid = start_price
    ts = EPOCH_START_MS
    noise_sigma = start_price * NOISE_BPS / 10_000.0

    if not random_walk:
        # Flat base + jumps for an exaggerated reference model.
        candidates = list(range(3, ticks - 2))
        spikes = sorted(rng.sample(candidates, min(MOMENTUM_SPIKES, len(candidates))))
        for i in range(ticks):
            if i in spikes:
                mid += SPIKE_STEP_PTS
            mid += gaussian(rng, noise_sigma)
            series.append((ts, mid))
            ts += TICK_INTERVAL_MS
        return series

    # Momentum random walk with a persistent drift term so the edge survives
    # feed latency AND the simulated execution delay long enough to capture.
    step = 0.0
    walk_rng = random.Random(seed + 7)          # decouple spikes from the walk
    spikes = spikes_at(ticks, walk_rng)
    for i in range(ticks):
        # AR(1) velocity: persistence keeps runs going, drift gives direction.
        step = (PERSISTENCE * step) + TREND_DRIFT_PTS + gaussian(rng, STEP_NOISE_PTS)
        mid += step
        if i in spikes:
            mid += SPIKE_STEP_PTS
        series.append((ts, mid))
        ts += TICK_INTERVAL_MS
    return series


def spikes_at(ticks: int, rng: random.Random) -> set[int]:
    candidates = list(range(8, ticks - 4))
    return set(rng.sample(candidates, min(MOMENTUM_SPIKES, len(candidates))))


def write_csv(f, ts: int, mid: float, half_spread: float) -> None:
    bid = mid - half_spread
    ask = mid + half_spread
    f.write(f"{ts},{bid:.2f},{ask:.2f},1.0\n")


def generate(args) -> None:
    out_dir = Path(args.out).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)
    lead_csv = out_dir / "lead.csv"
    lag_csv = out_dir / "lag.csv"

    lead = gen_lead(args.ticks, args.start, args.seed, args.random_walk)

    # The lag feed is the lead price as observed `lag_delay_ms` earlier,
    # degraded by the wider retail spread.
    delay_ticks = max(1, args.lag_delay_ms // TICK_INTERVAL_MS)

    with open(lead_csv, "w", newline="") as f_lead, \
         open(lag_csv, "w", newline="") as f_lag:
        f_lead.write("timestamp,bid,ask,volume\n")
        f_lag.write("timestamp,bid,ask,volume\n")

        for i, (ts, lead_mid) in enumerate(lead):
            write_csv(f_lead, ts, lead_mid, args.lead_spread / 2.0)
            j = max(0, i - delay_ticks)          # lag sees the stale lead price
            lag_mid = lead[j][1]
            write_csv(f_lag, ts, lag_mid, args.lag_spread / 2.0)

    print(f"wrote {lead_csv}")
    print(f"wrote {lag_csv}")
    print(f"  lead:  {args.ticks} ticks, base {args.start:.0f}, "
          f"spread {args.lead_spread:.2f}")
    print(f"  lag:   {args.ticks} ticks, +{args.lag_delay_ms} ms latency, "
          f"spread {args.lag_spread:.2f}, {SPIKE_STEP_PTS:.0f}-pt x "
          f"{MOMENTUM_SPIKES} spikes")
    if args.random_walk:
        print(f"  mode:  momentum random walk (p={PERSISTENCE}, "
              f"drift={TREND_DRIFT_PTS:.2f} pts/tick)")


def parse_args(argv) -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Generate mock lead/lag tick CSVs for tick_replay.")
    p.add_argument("--out", default=".", help="output directory (default: .)")
    p.add_argument("--ticks", type=int, default=20_000,
                   help="number of lead ticks (default 20000)")
    p.add_argument("--start", type=float, default=60_000.0,
                   help="base lead price (default 60000)")
    p.add_argument("--seed", type=int, default=42, help="RNG seed (default 42)")
    p.add_argument("--lead-spread", type=float, default=0.5,
                   help="lead half-spread in points (default 0.5)")
    p.add_argument("--lag-spread", type=float, default=1.0,
                   help="lag half-spread in points (default 1.0)")
    p.add_argument("--lag-delay-ms", type=int, default=10,
                   help="transport latency of the lag feed (default 10)")
    p.add_argument("--random-walk", action="store_true",
                   help="persistent momentum random walk (default off, i.e. "
                        "the historic flat base+noise+spikes model)")
    return p.parse_args(argv)


if __name__ == "__main__":
    generate(parse_args(sys.argv[1:]))