// =============================================================================
// CTraderExecutor — asynchronous market-order execution against the cTrader
// Open API (IC Markets) over Protobuf + TLS.
//
// Wire format: [4-byte big-endian length][ serialized ProtoMessage ] over TLS.
// See include/llm/ctrader_executor.h for the contract and threading model.
// =============================================================================

#include "llm/ctrader_executor.h"

#include <cctype>
#include <chrono>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <sstream>

#include <openssl/ssl.h>

#include <boost/asio/read.hpp>
#include <boost/asio/write.hpp>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/message.h>
#include <google/protobuf/reflection.h>

// Generated by protoc from third_party/openapi/*.proto (see CMakeLists.txt).
#include "OpenApiCommonMessages.pb.h"
#include "OpenApiCommonModelMessages.pb.h"
#include "OpenApiMessages.pb.h"
#include "OpenApiModelMessages.pb.h"

namespace llm {

namespace {

using google::protobuf::FieldDescriptor;
using google::protobuf::Message;
using google::protobuf::Reflection;

namespace asio = boost::asio;
using tcp  = asio::ip::tcp;
using ssl  = asio::ssl;
using SslStream = asio::ssl::stream<boost::asio::ip::tcp::socket>;

// ---- official ProtoOAPayloadType values (OpenApiModelMessages.proto) -----
namespace payload {
constexpr int32_t APPLICATION_AUTH_REQ = 2100;
constexpr int32_t APPLICATION_AUTH_RES = 2101;
constexpr int32_t ACCOUNT_AUTH_REQ     = 2102;
constexpr int32_t ACCOUNT_AUTH_RES     = 2103;
constexpr int32_t NEW_ORDER_REQ        = 2106;
constexpr int32_t SYMBOLS_LIST_REQ     = 2114;
constexpr int32_t SYMBOLS_LIST_RES     = 2115;
constexpr int32_t SYMBOL_BY_ID_REQ     = 2116;
constexpr int32_t SYMBOL_BY_ID_RES     = 2117;
constexpr int32_t SUBSCRIBE_SPOTS_REQ  = 2127;
constexpr int32_t SUBSCRIBE_SPOTS_RES  = 2128;
constexpr int32_t EXECUTION_EVENT      = 2126;
constexpr int32_t ORDER_ERROR_EVENT    = 2132;
constexpr int32_t SPOT_EVENT           = 2131;
constexpr int32_t ERROR_RES            = 2142;
constexpr int32_t CLIENT_DISCONNECT    = 2148;
}  // namespace payload

// Price fields are uint64 * 1/100000 (e.g. 123000 means 1.23).
constexpr int64_t kPriceScale = 100000;

// --- reflection helpers (fields are fetched by name to stay tolerant of
//     optional-field-absent on responses) -----------------------------------
const FieldDescriptor* fld(const Message& m, const char* name) {
    return m.GetDescriptor()->FindFieldByName(name);
}

int64_t  i64(const Message& m, const char* name) { const FieldDescriptor* f = fld(m, name); return f ? m.GetReflection()->GetInt64(m, f) : 0; }
uint64_t u64(const Message& m, const char* name) { const FieldDescriptor* f = fld(m, name); return f ? m.GetReflection()->GetUInt64(m, f) : 0; }
int32_t  i32(const Message& m, const char* name) { const FieldDescriptor* f = fld(m, name); return f ? m.GetReflection()->GetInt32(m, f) : 0; }
std::string str(const Message& m, const char* name) {
    const FieldDescriptor* f = fld(m, name);
    return f ? m.GetReflection()->GetString(m, f) : std::string();
}
std::string enum_name(const Message& m, const char* name) {
    const FieldDescriptor* f = fld(m, name);
    if (!f || f->type() != FieldDescriptor::TYPE_ENUM) return std::string();
    const auto* ev = m.GetReflection()->GetEnum(m, f);
    return ev ? ev->name() : std::string();
}

void set_str(Message* m, const char* name, const std::string& v) {
    const FieldDescriptor* f = fld(*m, name);
    if (f) m->GetReflection()->SetString(m, f, v);
}
void set_i64(Message* m, const char* name, int64_t v) {
    const FieldDescriptor* f = fld(*m, name);
    if (f) m->GetReflection()->SetInt64(m, f, v);
}
void set_enum_by_name(Message* m, const char* name, const char* ev_name) {
    const FieldDescriptor* f = fld(*m, name);
    if (!f || f->type() != FieldDescriptor::TYPE_ENUM) return;
    const auto* ev = f->enum_type()->FindValueByName(ev_name);
    if (ev) m->GetReflection()->SetEnum(m, f, ev);
}
void add_repeated_i64(Message* m, const char* name, int64_t v) {
    const FieldDescriptor* f = fld(*m, name);
    if (f && f->is_repeated()) m->GetReflection()->AddInt64(m, f, v);
}

}  // namespace

// ---------------------------------------------------------------------------
// Lifecycle
// ---------------------------------------------------------------------------
CTraderExecutor::CTraderExecutor(const Config& cfg) : cfg_(cfg) {
    // cTrader requires the ctidTraderAccountId as a number; parse defensively.
    char* end = nullptr;
    long long id = std::strtoll(cfg_.ctrader_account_id.c_str(), &end, 10);
    account_id_ = (end && *end == '\0') ? static_cast<int64_t>(id) : 0;
    if (!cfg_.ctrader_host.empty()) host_ = cfg_.ctrader_host;
    if (!cfg_.ctrader_port.empty()) port_ = cfg_.ctrader_port;
}
CTraderExecutor::~CTraderExecutor() { stop(); }

void CTraderExecutor::start() {
    bool expected = false;
    if (!running_.compare_exchange_strong(expected, true)) return;
    stopped_.store(false);
    thread_ = std::thread(&CTraderExecutor::worker_loop, this);
}

void CTraderExecutor::stop() {
    stopped_.store(true);
    { std::lock_guard<std::mutex> lk(mtx_); wake_ = true; }
    cv_.notify_all();
    if (thread_.joinable()) thread_.join();
    if (stream_) disconnect();
    running_.store(false);
}

void CTraderExecutor::execute(const std::string& symbol, const std::string& side,
                              double volume, double stoploss_pips,
                              double takeprofit_pips) {
    OrderJob j;
    j.symbol = symbol;
    j.side = side;
    j.volume = volume;
    j.stoploss_pips = stoploss_pips;
    j.takeprofit_pips = takeprofit_pips;
    bool dropped = false;
    {
        std::lock_guard<std::mutex> lk(mtx_);
        if (jobs_.size() >= queue_limit_) dropped = true;
        else jobs_.push_back(std::move(j));
        wake_ = true;
    }
    cv_.notify_all();
    if (dropped)
        std::fprintf(stderr, "[ctrader] queue full, order dropped (symbol=%s)\n",
                     symbol.c_str());
}

bool CTraderExecutor::connected() const {
    return connected_.load() && stream_ != nullptr;
}

void CTraderExecutor::set_result_callback(void (*cb)(const CTraderExecutionResult&, void*),
                                          void* userdata) {
    cb_ = cb;
    cb_data_ = userdata;
}

// ---------------------------------------------------------------------------
// Worker: persistent connection, serialized orders, reconnect-with-one-retry
// ---------------------------------------------------------------------------
void CTraderExecutor::worker_loop() {
    std::fprintf(stderr, "[ctrader] worker started\n");
    while (!stopped_.load()) {
        OrderJob job;
        {
            std::unique_lock<std::mutex> lk(mtx_);
            cv_.wait(lk, [this] { return wake_ || stopped_.load(); });
            if (stopped_.load()) break;
            if (jobs_.empty()) { wake_ = false; continue; }
            job = std::move(jobs_.front());
            jobs_.pop_front();
            wake_ = !jobs_.empty();
        }

        if (!connected()) {
            if (!connect()) {
                std::fprintf(stderr, "[ctrader] connect failed, worker sleeping\n");
                std::this_thread::sleep_for(std::chrono::seconds(3));
                continue;    // job dropped on connection failure (backpressure)
            }
        }

        CTraderExecutionResult r;
        for (int attempt = 1; attempt <= 2; ++attempt) {
            r = send_market_order(job);
            if (!r.ok) {
                std::fprintf(stderr, "[ctrader] order attempt %d failed: %s\n",
                             attempt, r.error.c_str());
            }
            // If the failure was a transport-level error (~1% of cases), retry
            // once after a full reconnect + re-auth.
            if (r.ok) break;
            if (attempt == 1) {
                disconnect();
                if (connect()) continue;
            }
            break;
        }

        if (cb_) cb_(r, cb_data_);
        std::fprintf(stderr,
                     "[ctrader] symbol=%s side=%s vol=%.2f -> status=%s "
                     "latency=%.2f ms\n",
                     job.symbol.c_str(), job.side.c_str(), job.volume,
                     r.status.c_str(), r.latency_ms);
    }
    std::fprintf(stderr, "[ctrader] worker stopped\n");
}

// ---------------------------------------------------------------------------
// connect / authenticate / resolve / subscribe (worker thread only)
// ---------------------------------------------------------------------------
bool CTraderExecutor::connect() {
    boost::system::error_code ec;
    try {
        if (stream_ && stream_->next_layer().is_open()) disconnect();

        ssl_.set_verify_mode(ssl::verify_none);   // latency — prod: verify_peer
        stream_ = std::make_unique<SslStream>(io_, ssl_);
        // SNI must be set on the raw OpenSSL handle before handshake.
        const int sni_rc = SSL_set_tlsext_host_name(stream_->native_handle(),
                                                    host_.c_str());
        if (sni_rc != 1)
            std::fprintf(stderr, "[ctrader] SNI warning for %s\n", host_.c_str());
        stream_->next_layer().set_option(asio::ip::tcp::no_delay(true), ec);
        tcp::resolver resolver(io_);
        const auto endpoints = resolver.resolve(host_, port_);
        asio::connect(stream_->next_layer(), endpoints);
        stream_->handshake(ssl::stream_base::client);
        connected_.store(true);
        std::fprintf(stderr, "[ctrader] TLS connected %s:%s\n", host_.c_str(),
                     port_.c_str());

        std::string error;
        if (!authenticate(&error)) {
            std::fprintf(stderr, "[ctrader] auth failed: %s\n", error.c_str());
            disconnect();
            return false;
        }

        const std::string sym = cfg_.ctrader_symbol.empty()
                                    ? "XAU/USD"
                                    : cfg_.ctrader_symbol;
        if (!resolve_symbol(sym, &syminfo_, &error)) {
            std::fprintf(stderr, "[ctrader] resolve symbol %s failed: %s\n",
                         sym.c_str(), error.c_str());
            disconnect();
            return false;
        }
        if (!subscribe_spot(&error)) {
            std::fprintf(stderr, "[ctrader] subscribe spots failed: %s\n",
                         error.c_str());
            disconnect();
            return false;
        }
        std::fprintf(stderr,
                     "[ctrader] ready: symbol=%s symbolId=%lld lotSize=%lld\n",
                     sym.c_str(), static_cast<long long>(syminfo_.symbol_id),
                     static_cast<long long>(syminfo_.lot_size));
        return true;
    } catch (const std::exception& e) {
        std::fprintf(stderr, "[ctrader] connect exception: %s\n", e.what());
        disconnect();
        return false;
    }
}

void CTraderExecutor::disconnect() {
    connected_.store(false);
    if (stream_) {
        try { stream_->next_layer().shutdown(tcp::socket::shutdown_both); }
        catch (...) { /* best-effort */ }
        stream_.reset();
    }
    spot_bid_.store(0.0);
    spot_ask_.store(0.0);
}

bool CTraderExecutor::authenticate(std::string* error) {
    // 1) Application auth (Client ID + Secret).
    ::ProtoOAApplicationAuthReq req;
    set_str(&req, "clientId", cfg_.ctrader_client_id);
    set_str(&req, "clientSecret", cfg_.ctrader_client_secret);
    std::string body;
    if (!req.SerializeToString(&body)) { if (error) *error = "serialize app req"; return false; }

    { std::string e;
      std::string resp = exchange(payload::APPLICATION_AUTH_REQ, body,
                                  payload::APPLICATION_AUTH_RES, &e);
      if (resp.empty()) { if (error) *error = e.empty() ? "app auth timed out" : e; return false; } }

    // 2) Account auth.
    ::ProtoOAAccountAuthReq acc;
    set_i64(&acc, "ctidTraderAccountId", account_id_);
    set_str(&acc, "accessToken", cfg_.ctrader_access_token);
    body.clear();
    if (!acc.SerializeToString(&body)) { if (error) *error = "serialize acc req"; return false; }

    std::string e;
    std::string resp = exchange(payload::ACCOUNT_AUTH_REQ, body,
                                payload::ACCOUNT_AUTH_RES, &e);
    if (resp.empty()) { if (error) *error = e.empty() ? "account auth timed out" : e; return false; }
    return true;
}

bool CTraderExecutor::resolve_symbol(const std::string& sym, SymbolInfo* out,
                                     std::string* error) {
    // List symbols, find by normalized name.
    ::ProtoOASymbolsListReq list;
    set_i64(&list, "ctidTraderAccountId", account_id_);
    std::string body;
    if (!list.SerializeToString(&body)) { *error = "serialize list req"; return false; }
    std::string resp = exchange(payload::SYMBOLS_LIST_REQ, body,
                                payload::SYMBOLS_LIST_RES, error);
    if (resp.empty()) return false;
    ::ProtoOASymbolsListRes listRes;
    if (!listRes.ParseFromString(resp)) { *error = "parse list res"; return false; }

    // Normalize broker symbol name: strip whitespace/slash, uppercase.
    auto norm = [](const std::string& s) {
        std::string o;
        for (char c : s)
            if (std::isalnum(static_cast<unsigned char>(c)))
                o.push_back(static_cast<char>(
                    std::toupper(static_cast<unsigned char>(c))));
        return o;
    };
    const std::string want = norm(sym);
    int64_t id = 0;
    for (int i = 0; i < listRes.symbol_size(); ++i) {
        const auto& ls = listRes.symbol(i);
        const std::string name = norm(str(ls, "symbolName"));
        if (name == want) { id = i64(ls, "symbolId"); break; }
    }
    if (id == 0) { if (error) *error = "symbol not found: " + sym; return false; }

    // Fetch full symbol metadata (digits, pip position, lot size).
    ::ProtoOASymbolByIdReq byid;
    set_i64(&byid, "ctidTraderAccountId", account_id_);
    add_repeated_i64(&byid, "symbolId", id);
    body.clear();
    if (!byid.SerializeToString(&body)) { *error = "serialize by-id req"; return false; }
    resp = exchange(payload::SYMBOL_BY_ID_REQ, body, payload::SYMBOL_BY_ID_RES, error);
    if (resp.empty()) return false;
    ::ProtoOASymbolByIdRes byRes;
    if (!byRes.ParseFromString(resp)) { *error = "parse by-id res"; return false; }
    if (byRes.symbol_size() == 0) { *error = "empty symbol-by-id res"; return false; }
    const auto& sp = byRes.symbol(0);
    out->symbol_id = id;
    out->digits = i32(sp, "digits");
    out->pip_position = i32(sp, "pipPosition");
    out->lot_size = i64(sp, "lotSize");   // 1 lot in 0.01-unit volume terms
    if (out->lot_size <= 0) out->lot_size = 1000000;  // 1 FX lot fallback
    out->valid = true;
    return true;
}

bool CTraderExecutor::subscribe_spot(std::string* error) {
    ::ProtoOASubscribeSpotsReq req;
    set_i64(&req, "ctidTraderAccountId", account_id_);
    add_repeated_i64(&req, "symbolId", syminfo_.symbol_id);
    std::string body;
    if (!req.SerializeToString(&body)) { *error = "serialize subscribe req"; return false; }
    std::string resp = exchange(payload::SUBSCRIBE_SPOTS_REQ, body,
                                payload::SUBSCRIBE_SPOTS_RES, error);
    if (resp.empty()) return false;

    // Wait for the first spot snapshot so we have a reference price.
    const auto deadline = std::chrono::steady_clock::now() + std::chrono::seconds(5);
    while (std::chrono::steady_clock::now() < deadline) {
        bool ok = false;
        std::string raw = read_frame(ok);
        if (!ok) { if (error) *error = "read failed during subscribe"; return false; }
        ::ProtoMessage pm;
        if (!pm.ParseFromString(raw)) continue;
        const uint32_t type = pm.payloadtype();
        if (type == payload::SPOT_EVENT) {
            ::ProtoOASpotEvent ev;
            if (ev.ParseFromString(pm.payload())) {
                if (i64(ev, "symbolId") == syminfo_.symbol_id) {
                    const uint64_t bid = u64(ev, "bid");
                    const uint64_t ask = u64(ev, "ask");
                    spot_bid_.store(static_cast<double>(bid) / kPriceScale);
                    spot_ask_.store(static_cast<double>(ask) / kPriceScale);
                    return true;
                }
            }
        }
    }
    if (error) *error = "spot snapshot not received";
    return false;
}

// ---------------------------------------------------------------------------
// Order placement
// ---------------------------------------------------------------------------
CTraderExecutionResult CTraderExecutor::send_market_order(const OrderJob& job) {
    bool transport = false;
    CTraderExecutionResult r;
    try {
        r = place_order(job, &transport);
    } catch (...) {
        r.ok = false;
        r.error = "exception";
        transport = true;
    }
    return r;
}

CTraderExecutionResult CTraderExecutor::place_order(const OrderJob& job,
                                                    bool* transport_failed) {
    CTraderExecutionResult r;
    *transport_failed = false;

    // Resolve symbol id (use cached if matches, else re-resolve).
    SymbolInfo info = syminfo_;
    if (!info.valid || info.symbol_id == 0) {
        std::string e;
        if (!resolve_symbol(job.symbol, &info, &e)) { r.error = "symbol resolve: " + e; return r; }
        syminfo_ = info;
    }

    const bool buy = (job.side == "buy" || job.side == "BUY");
    const int64_t volume_proto = std::llround(job.volume * static_cast<double>(info.lot_size));
    // Convert a pips distance to Proto relative SL/TP. relativeStopLoss /
    // relativeTakeProfit are stored as 1/100000 of a price unit (kPriceScale),
    // and 1 pip == 10^(-pip_position) price units — so 1 pip in protocol units
    // is 10^(5 - pip_position). (e.g. EUR/USD pip_position=4 -> 10 protocol units.)
    const double pip_proto = std::pow(10.0, static_cast<double>(5 - info.pip_position));
    const int64_t rel_sl = static_cast<int64_t>(std::llround(job.stoploss_pips * pip_proto));
    const int64_t rel_tp = static_cast<int64_t>(std::llround(job.takeprofit_pips * pip_proto));

    ::ProtoOANewOrderReq req;
    set_i64(&req, "ctidTraderAccountId", account_id_);
    set_i64(&req, "symbolId", info.symbol_id);
    set_enum_by_name(&req, "orderType", "MARKET");
    set_enum_by_name(&req, "tradeSide", buy ? "BUY" : "SELL");
    set_i64(&req, "volume", volume_proto);
    if (rel_sl > 0) set_i64(&req, "relativeStopLoss", rel_sl);
    if (rel_tp > 0) set_i64(&req, "relativeTakeProfit", rel_tp);
    if (rel_sl > 0 || rel_tp > 0) set_enum_by_name(&req, "stopTriggerMethod", "TRADE");

    std::string clientOrderId = "LL" + std::to_string(++next_id_);
    set_str(&req, "clientOrderId", clientOrderId);

    std::string body;
    if (!req.SerializeToString(&body)) { r.error = "serialize order req"; return r; }

    const auto t0 = std::chrono::high_resolution_clock::now();
    std::string error;
    std::string resp = exchange(payload::NEW_ORDER_REQ, body,
                                payload::EXECUTION_EVENT, &error);
    if (resp.empty()) {
        *transport_failed = (error.find("transport") != std::string::npos);
        r.error = error.empty() ? "no execution event (timeout)" : error;
        return r;
    }
    const auto t1 = std::chrono::high_resolution_clock::now();
    r.latency_ms = std::chrono::duration<double, std::milli>(t1 - t0).count();

    ::ProtoOAExecutionEvent ev;
    if (!ev.ParseFromString(resp)) { r.error = "parse execution event"; return r; }
    r.status = enum_name(ev, "executionType");
    // Nest: order / position are message fields; pull ids via reflection.
    const FieldDescriptor* of = ev.GetDescriptor()->FindFieldByName("order");
    if (of) {
        const Message& ord = ev.GetReflection()->GetMessage(ev, of);
        r.order_id = i64(ord, "orderId");
    }
    const FieldDescriptor* pf = ev.GetDescriptor()->FindFieldByName("position");
    if (pf && ev.GetReflection()->HasField(ev, pf)) {
        const Message& pos = ev.GetReflection()->GetMessage(ev, pf);
        r.position_id = i64(pos, "positionId");
    }
    // Execution-event enum names are ORDER_ACCEPTED / ORDER_FILLED / ... — map
    // them to the public short status strings used by the engine.
    if (r.status == "ORDER_ACCEPTED") r.status = "ACCEPTED";
    else if (r.status == "ORDER_FILLED") r.status = "FILLED";
    else if (r.status == "ORDER_REJECTED") r.status = "REJECTED";
    r.ok = (r.status == "ACCEPTED" || r.status == "FILLED");
    if (!r.ok && r.error.empty()) r.error = "order rejected: " + r.status;
    return r;
}

// ---------------------------------------------------------------------------
// Wire helpers
// ---------------------------------------------------------------------------
bool CTraderExecutor::send_frame(const std::string& payload) {
    if (!stream_ || !stream_->next_layer().is_open()) return false;
    uint8_t hdr[4];
    const uint32_t n = static_cast<uint32_t>(payload.size());
    hdr[0] = static_cast<uint8_t>((n >> 24) & 0xFF);
    hdr[1] = static_cast<uint8_t>((n >> 16) & 0xFF);
    hdr[2] = static_cast<uint8_t>((n >> 8) & 0xFF);
    hdr[3] = static_cast<uint8_t>(n & 0xFF);
    boost::system::error_code ec;
    asio::write(*stream_, asio::buffer(hdr, 4), asio::transfer_exactly(4), ec);
    if (ec) return false;
    asio::write(*stream_, asio::buffer(payload), asio::transfer_exactly(n), ec);
    return !ec;
}

std::string CTraderExecutor::read_frame(bool& ok) {
    uint8_t len[4];
    boost::system::error_code ec;
    size_t got = asio::read(*stream_, asio::buffer(len, 4), asio::transfer_exactly(4), ec);
    if (ec || got != 4) { ok = false; return {}; }
    const uint32_t n = (uint32_t(len[0]) << 24) | (uint32_t(len[1]) << 16) |
                       (uint32_t(len[2]) << 8) | uint32_t(len[3]);
    if (n == 0 || n > (1u << 20)) { ok = false; return {}; }   // sanity cap 1 MB
    std::string body(n, '\0');
    size_t rd = asio::read(*stream_, asio::buffer(&body[0], n), asio::transfer_exactly(n), ec);
    ok = (rd == n && !ec);
    return ok ? body : std::string();
}

std::string CTraderExecutor::exchange(int32_t ptype, const std::string& body,
                                      int32_t expect_type, std::string* error) {
    ::ProtoMessage out;
    out.set_payloadtype(static_cast<uint32_t>(ptype));
    out.set_payload(body);
    std::string raw;
    if (!out.SerializeToString(&raw)) { if (error) *error = "serialize ProtoMessage"; return {}; }
    if (!send_frame(raw)) { if (error) *error = "send failed (transport)"; return {}; }

    for (;;) {
        bool ok = false;
        std::string fraw = read_frame(ok);
        if (!ok) { if (error) *error = "read failed (transport)"; return {}; }
        ::ProtoMessage pm;
        if (!pm.ParseFromString(fraw)) continue;
        const int32_t got = static_cast<int32_t>(pm.payloadtype());
        if (got == expect_type) return pm.payload();
        // No match: dispatch advisory/err events, keep reading.
        std::string ls;
        if (dispatch_other(pm.payload(), got, &ls)) { if (error) *error = ls; return {}; }
    }
}

bool CTraderExecutor::dispatch_other(const std::string& raw, int32_t type,
                                     std::string* error) {
    switch (type) {
        case payload::SPOT_EVENT: {
            ::ProtoOASpotEvent ev;
            if (!ev.ParseFromString(raw)) break;
            const uint64_t bid = u64(ev, "bid");
            const uint64_t ask = u64(ev, "ask");
            spot_bid_.store(static_cast<double>(bid) / kPriceScale);
            spot_ask_.store(static_cast<double>(ask) / kPriceScale);
            break;   // not an error
        }
        case payload::ORDER_ERROR_EVENT: {
            if (error) *error = "order rejected: " + raw.substr(0, 64);
            return true;   // stop exchange with error
        }
        case payload::ERROR_RES: {
            if (error) *error = "api error: " + raw.substr(0, 64);
            return true;
        }
        case payload::CLIENT_DISCONNECT: {
            if (error) *error = "client disconnected by server";
            return true;
        }
        default:
            break;   // heartbeat / unsolicited events — ignore
    }
    return false;
}

}  // namespace llm